/* memo-v25 */
icon.memo='📝';
const memoMenusV25=[['calendar','달력'],['add','추가'],['memo','메모'],['focus','집중'],['mood','감정'],['money','가계부'],['invest','투자수익'],['route','이동'],['clients','클라이언트'],['wish','위시']];
function loadMemos(){return load('todoAdhdMemos',[])}
function saveMemos(v){store('todoAdhdMemos',v)}
function memoCategory(text){const t=String(text||'');if(/회의|미팅|클라이언트|고객|연락|피드백|업무|마케팅|브랜딩/i.test(t))return '업무/클라이언트';if(/돈|지출|가계부|빚|상환|저축|비상금|결제|카드/i.test(t))return '돈/가계';if(/주식|코인|투자|차트|매매|수익|손실|복기/i.test(t))return '투자';if(/아이디어|기획|콘텐츠|영상|릴스|유튜브|촬영|편집/i.test(t))return '아이디어/콘텐츠';if(/불안|우울|힘들|빡|화남|멘붕|피곤|감정|기분|외롭/i.test(t))return '감정 기록';if(/사고싶|위시|워너비|갖고싶|여행|데이트|친구/i.test(t))return '위시/생활';if(/병원|약속|이동|출발|도착|주소|장소/i.test(t))return '이동/약속';if(/해야|내일|다음주|마감|제출|보고서|기획서|예약/i.test(t))return '일정 후보';return '일반 메모'}
function memoHint(cat){return {'업무/클라이언트':'나중에 클라이언트 탭이나 일정으로 옮기기 좋아.','돈/가계':'가계부나 빚 상환 기록으로 연결할 수 있어.','투자':'투자수익 탭에서 복기하면 감정 기록까지 같이 남길 수 있어.','아이디어/콘텐츠':'흩어지기 쉬운 아이디어니까 제목만 따로 다시 뽑아두면 좋아.','감정 기록':'감정 탭 일기와 같이 보면 패턴이 보여.','위시/생활':'바로 사기보다 24시간 보류 리스트로 두면 충동을 줄일 수 있어.','이동/약속':'이동 탭에서 출발지와 도착지로 계산해봐.','일정 후보':'추가 탭에 붙여넣으면 날짜별 일정으로 쪼갤 수 있어.','일반 메모':'지금은 보관만 해도 충분해.'}[cat]||'보관 완료'}
function memoTime(ts){try{return new Date(ts).toLocaleString('ko-KR',{dateStyle:'medium',timeStyle:'short'})}catch{return ''}}
function renderMenus(){const html=memoMenusV25.map(([id,label])=>`<button class="${view===id?'active':''}" data-view="${id}">${icon[id]||'•'} ${label}</button>`).join('');$('#sideMenu').innerHTML=html;$('#mobileNav').innerHTML=memoMenusV25.slice(0,5).map(([id,label])=>`<button class="${view===id?'active':''}" data-view="${id}">${icon[id]||'•'}<br>${label}</button>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view==='stickers'?'calendar':b.dataset.view;render()});}
function renderMemo(){const memos=loadMemos();const groups=[...new Set(memos.map(m=>m.category))];$('#main').innerHTML=`<section class="section-title"><div><h2>메모장</h2><p>와다다 떠오른 생각을 일단 저장해. 쓴 시간과 자동분류를 같이 남겨둘게.</p></div></section><div class="memo-form"><textarea id="memoText" placeholder="생각나는 거 그대로 적어. 예: 병원 기획서 아이디어, 클라이언트 연락할 말, 갑자기 사고 싶은 것, 투자 복기..."></textarea><button class="primary" id="saveMemo">메모 저장 + 자동분류</button><p class="muted">메모는 일정/일기와 분리해서 저장돼. 필요할 때만 일정 후보로 옮기면 돼.</p></div><div class="divider"></div><div class="memo-filter">${['전체',...groups].map(g=>`<button class="ghost" data-memo-filter="${safe(g)}">${safe(g)}</button>`).join('')}</div><div class="cards memo-list" id="memoList">${memoListHtml(memos)}</div>`;$('#saveMemo').onclick=saveMemo;document.querySelectorAll('[data-memo-filter]').forEach(b=>b.onclick=()=>{$('#memoList').innerHTML=memoListHtml(loadMemos(),b.dataset.memoFilter)})}
function memoListHtml(memos,filter='전체'){const list=(filter==='전체'?memos:memos.filter(m=>m.category===filter));if(!list.length)return '<p class="muted">아직 저장된 메모가 없어. 오늘 머릿속에서 제일 시끄러운 것 하나만 적어도 돼.</p>';return list.map(m=>`<article class="memo-card"><div><span class="memo-cat">${safe(m.category)}</span><time>${safe(memoTime(m.createdAt))}</time></div><p>${safe(m.text)}</p><small>${safe(memoHint(m.category))}</small><button class="ghost" data-delete-memo="${m.id}">삭제</button></article>`).join('')}
function saveMemo(){const text=$('#memoText').value.trim();if(!text){toast('메모 내용을 먼저 적어줘.');return}const category=memoCategory(text),memos=loadMemos();memos.unshift({id:Date.now(),text,category,createdAt:new Date().toISOString()});saveMemos(memos);toast(`${category}로 자동분류해서 저장했어.`);renderMemo();renderPanel()}
function deleteMemo(id){const memos=loadMemos().filter(m=>String(m.id)!==String(id));saveMemos(memos);renderMemo();}
document.addEventListener('click',e=>{const id=e.target?.dataset?.deleteMemo;if(id)deleteMemo(id)});
const renderBaseV25=render;
render=function(){renderMenus(); if(view==='calendar')renderCalendar(); if(view==='add')renderAdd(); if(view==='memo')renderMemo(); if(view==='focus')renderFocus(); if(view==='stickers')renderStickerPage(); if(view==='mood')renderMood(); if(view==='money')renderMoney(); if(view==='invest')renderInvest(); if(view==='route')renderRoute(); if(view==='clients')renderClients(); if(view==='wish')renderWish(); renderPanel();}
try{render()}catch(e){}
